services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: songregistry
      MYSQL_USER: bart
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  app:
    image: songregistry-container
    container_name: songregistry-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-container:3307/songregistry
      SPRING_DATASOURCE_USERNAME: bart
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:

volumes:
  db_data:

