name: backend tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: songregistry
          MYSQL_USER: bart
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build backend with Maven
      run: mvn -B clean package --file ${{ github.workspace }}/songregistry-backend/pom.xml

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

    - name: Run tests with Docker Compose
      run: |
        docker-compose -f ${{ github.workspace }}/songregistry-backend/compose.yaml up --build -d
        sleep 30 # wait for services to be ready
        mvn -B test --file ${{ github.workspace }}/songregistry-backend/pom.xml

    - name: Shut down services
      run: docker-compose -f ${{ github.workspace }}/docker-compose.yml down
