name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install
        working-directory: ./

      # Step 5 Install dependencies for main frontend
      - name: Install dependencies for main frontend
        run: pnpm install
        working-directory: ./songregistry-frontend

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm build
          start: pnpm start
          working-directory: ./songregistry-frontend
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome

