name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: songregistry
          MYSQL_USER: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --password=root" --health-timeout=5s --health-retries=5

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies for the frontend
      - name: Install dependencies for main frontend
        run: pnpm install
        working-directory: ./songregistry-frontend

      # Step 5: Install dependencies for the backend (Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 6: Build the backend with Maven
      - name: Build backend with Maven
        run: mvn -B clean package --file ./songregistry-backend/pom.xml

      # Step 7: Start backend server
      - name: Start backend
        run: mvn spring-boot:run --file ./songregistry-backend/pom.xml &

      # Step 8: Wait for MariaDB to be ready
      - name: Wait for MariaDB to be ready
        run: |
          sleep 15  # Adjust the wait time to allow MariaDB to start up

      # Step 9: Import the SQL file into MariaDB
      - name: Import SQL file into MariaDB
        run: |
          mysql -h 127.0.0.1 -u root -proot songregistry < ./database/songregistry.sql
        env:
          MYSQL_ROOT_PASSWORD: root

      # Step 10: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: pnpm run dev
          working-directory: ./songregistry-frontend
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome
