name: CodeQualityAnalsis
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
    CQA:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install -r 
              
            - name: Run Code quality lint tests for Klant
              working-directory: ./songregistry-frontend
              run: pnpm npx eslint

            - name: Run Code quality lint tests for Admin
              working-directory: ./songregistry-admin-frontend
              run: pnpm npx eslint
